## This is the Capstone Project Notebook.

In [1]:
import pandas as pd
import numpy as np
#import sys
#!conda install --yes --prefix {sys.prefix} lxml
!conda install -c anaconda --yes lxml

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.8.1

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/jupyterlab/conda/envs/python

  added / updated specs:
    - lxml


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numpy-base-1.15.4          |   py36h81de0dd_0         4.2 MB  anaconda
    numpy-1.15.4               |   py36h1d66e8a_0          35 KB  anaconda
    openssl-1.1.1              |       h7b6447c_0         5.0 MB  anaconda
    lxml-4.3.0                 |   py36hefd8a0e_0         1.5 MB  anaconda
    mkl_fft-1.0.6              |   py36h7dd41cf_0         150 KB  anaconda
    certifi-2019.11.28         |           py36_0         156 KB  anaconda
    blas-1.0                   |              mkl           6 KB  anaconda
    scipy-1.1.0                |   py36hfa4b5c9_1        18.0 MB  anaconda
    mkl_random-1.0.1           |   py36h4414c95_1         373 KB  anaconda
    scikit-learn-0.20.1        |   py36h4989274_0         5.7 MB  anaconda
    ------------------------------------------------------------
                                           Total:        35.1 MB

The following packages will be UPDATED:

    certifi:      2019.11.28-py36_0                                  --> 2019.11.28-py36_0     anaconda
    lxml:         4.3.0-py36hefd8a0e_0                               --> 4.3.0-py36hefd8a0e_0  anaconda
    mkl_fft:      1.0.4-py37h4414c95_1                               --> 1.0.6-py36h7dd41cf_0  anaconda
    mkl_random:   1.0.1-py37h4414c95_1                               --> 1.0.1-py36h4414c95_1  anaconda
    numpy-base:   1.15.1-py37h81de0dd_0                              --> 1.15.4-py36h81de0dd_0 anaconda
    openssl:      1.1.1d-h7b6447c_3                                  --> 1.1.1-h7b6447c_0      anaconda

The following packages will be DOWNGRADED:

    blas:         1.1-openblas                           conda-forge --> 1.0-mkl               anaconda
    numpy:        1.16.2-py36_blas_openblash1522bff_0    conda-forge [blas_openblas] --> 1.15.4-py36h1d66e8a_0 anaconda
    scikit-learn: 0.20.1-py36_blas_openblashebff5e3_1200 conda-forge [blas_openblas] --> 0.20.1-py36h4989274_0 anaconda
    scipy:        1.2.1-py36_blas_openblash1522bff_0     conda-forge [blas_openblas] --> 1.1.0-py36hfa4b5c9_1  anaconda


Downloading and Extracting Packages
numpy-base-1.15.4    | 4.2 MB    | ##################################### | 100%
numpy-1.15.4         | 35 KB     | ##################################### | 100%
openssl-1.1.1        | 5.0 MB    | ##################################### | 100%
lxml-4.3.0           | 1.5 MB    | ##################################### | 100%
mkl_fft-1.0.6        | 150 KB    | ##################################### | 100%
certifi-2019.11.28   | 156 KB    | ##################################### | 100%
blas-1.0             | 6 KB      | ##################################### | 100%
scipy-1.1.0          | 18.0 MB   | ##################################### | 100%
mkl_random-1.0.1     | 373 KB    | ##################################### | 100%
scikit-learn-0.20.1  | 5.7 MB    | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

In [23]:
!conda install -c conda-forge geopy --yes # uncomment this line if you haven't completed the Foursquare API lab

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.8.1

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/jupyterlab/conda/envs/python

  added / updated specs:
    - geopy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    geopy-1.20.0               |             py_0          57 KB  conda-forge
    certifi-2019.11.28         |           py36_0         149 KB  conda-forge
    geographiclib-1.50         |             py_0          34 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         240 KB

The following NEW packages will be INSTALLED:

    geographiclib: 1.50-py_0         conda-forge
    geopy:         1.20.0-py_0       conda-forge

The following packages will be UPDATED:

    certifi:       2019.11.28-py36_0 anaconda    --> 2019.11.28-py36_0 conda-forge

The following packages will be DOWNGRADED:

    openssl:       1.1.1-h7b6447c_0  anaconda    --> 1.1.1d-h516909a_0 conda-forge


Downloading and Extracting Packages
geopy-1.20.0         | 57 KB     | ##################################### | 100%
certifi-2019.11.28   | 149 KB    | ##################################### | 100%
geographiclib-1.50   | 34 KB     | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

In [27]:
!conda install -c conda-forge geocoder --yes

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.8.1

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/jupyterlab/conda/envs/python

  added / updated specs:
    - geocoder


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    future-0.18.2              |           py36_0         713 KB  conda-forge
    click-7.0                  |             py_0          61 KB  conda-forge
    ratelim-0.1.6              |             py_2           6 KB  conda-forge
    geocoder-1.38.1            |             py_1          53 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         833 KB

The following NEW packages will be INSTALLED:

    future:   0.18.2-py36_0 conda-forge
    geocoder: 1.38.1-py_1   conda-forge
    ratelim:  0.1.6-py_2    conda-forge

The following packages will be UPDATED:

    click:    6.7-py37_0                --> 7.0-py_0 conda-forge


Downloading and Extracting Packages
future-0.18.2        | 713 KB    | ##################################### | 100%
click-7.0            | 61 KB     | ##################################### | 100%
ratelim-0.1.6        | 6 KB      | ##################################### | 100%
geocoder-1.38.1      | 53 KB     | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

In [10]:

url='https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'
df=pd.read_html(url, header=0)[0]

df.head(10)

  Postcode           Borough     Neighbourhood
0      M1A      Not assigned      Not assigned
1      M2A      Not assigned      Not assigned
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront
5      M6A        North York  Lawrence Heights
6      M6A        North York    Lawrence Manor
7      M7A  Downtown Toronto      Queen's Park
8      M8A      Not assigned      Not assigned
9      M9A      Queen's Park      Not assigned

Drop rows that a borough is Not assigned.

In [11]:
index_empty=df[df['Borough']=='Not assigned'].index
df.drop(index_empty,inplace=True)
df.reset_index(drop=True, inplace=True)
df.head(10)

  Postcode           Borough     Neighbourhood
0      M3A        North York         Parkwoods
1      M4A        North York  Victoria Village
2      M5A  Downtown Toronto      Harbourfront
3      M6A        North York  Lawrence Heights
4      M6A        North York    Lawrence Manor
5      M7A  Downtown Toronto      Queen's Park
6      M9A      Queen's Park      Not assigned
7      M1B       Scarborough             Rouge
8      M1B       Scarborough           Malvern
9      M3B        North York   Don Mills North

If a cell has a borough but a Not assigned neighborhood, then the neighborhood will be the same as the borough.

In [13]:
df['Neighbourhood'] = df.apply(
    lambda row: row['Borough'] if row['Neighbourhood']=='Not assigned' else row['Neighbourhood'],
    axis=1
)
df.head(10)

  Postcode           Borough     Neighbourhood
0      M3A        North York         Parkwoods
1      M4A        North York  Victoria Village
2      M5A  Downtown Toronto      Harbourfront
3      M6A        North York  Lawrence Heights
4      M6A        North York    Lawrence Manor
5      M7A  Downtown Toronto      Queen's Park
6      M9A      Queen's Park      Queen's Park
7      M1B       Scarborough             Rouge
8      M1B       Scarborough           Malvern
9      M3B        North York   Don Mills North

Merge postal code area

In [14]:
df_post=df.groupby(['Postcode'])['Neighbourhood'].apply(lambda x: ' ,'.join(x))

In [15]:
df_post=pd.DataFrame(data=df_post)
df_post.head()

                                   Neighbourhood
Postcode
M1B                               Rouge ,Malvern
M1C       Highland Creek ,Rouge Hill ,Port Union
M1E            Guildwood ,Morningside ,West Hill
M1G                                       Woburn
M1H                                    Cedarbrae

In [16]:
df1=df[['Postcode','Borough']].drop_duplicates()
df1.head()

  Postcode           Borough
0      M3A        North York
1      M4A        North York
2      M5A  Downtown Toronto
3      M6A        North York
5      M7A  Downtown Toronto

In [17]:
df1.set_index(['Postcode'],inplace=True)

In [20]:
df2= df1.merge(df_post, left_index=True, right_index=True)
df2.reset_index(inplace=True)
df2.head()

  Postcode           Borough                     Neighbourhood
0      M3A        North York                         Parkwoods
1      M4A        North York                  Victoria Village
2      M5A  Downtown Toronto                      Harbourfront
3      M6A        North York  Lawrence Heights ,Lawrence Manor
4      M7A  Downtown Toronto                      Queen's Park

In [21]:
df2.shape

(103, 3)

There are 103 rows in the dataset.

In [28]:
import geocoder # import geocoder

In [31]:
# initialize your variable to None
def get_postcode(postal_code):
    lat_lng_coords = None
    # loop until you get the coordinates
    while(lat_lng_coords is None):
        g = geocoder.google('{}, Toronto, Ontario'.format(postal_code))
    lat_lng_coords = g.latlng
    latitude = lat_lng_coords[0]
    longitude = lat_lng_coords[1]
    return [latitude,longitude]

In [34]:
postal_code='M3A'
geocoder.google('{}, Toronto, Ontario'.format(postal_code))

<[REQUEST_DENIED] Google - Geocode [empty]>

In [35]:
geourl='https://cocl.us/Geospatial_data'
df_geo=pd.read_csv(geourl)

In [36]:
df_geo.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [39]:
df3= df2.merge(df_geo, left_on='Postcode', right_on='Postal Code')

In [41]:
df3.head()

,Postcode,Borough,Neighbourhood,Postal Code,Latitude,Longitude
0,M3A,North York,Parkwoods,M3A,43.753259,-79.329656
1,M4A,North York,Victoria Village,M4A,43.725882,-79.315572
2,M5A,Downtown Toronto,Harbourfront,M5A,43.654260,-79.360636
3,M6A,North York,"Lawrence Heights ,Lawrence Manor",M6A,43.718518,-79.464763
4,M7A,Downtown Toronto,Queen's Park,M7A,43.662301,-79.389494